type QuestionType = "guess_the_book" | "fill_in_the_blank" | "who_said_it";

export type Difficulty = "easy" | "medium" | "hard";

export type QuestionSpec = {
  type: QuestionType;
  difficulty: Difficulty;
  reference: string;
  strip?: string;
  blank?: string;
  options: string[];
  answer: string;
};

export const TRANSLATION = "CPDV";

export const PROMPTS: Record<QuestionType, string> = {
  guess_the_book: "Which book of the Bible is this verse from?",
  fill_in_the_blank: "Which word completes the verse?",
  who_said_it: "Who spoke these words?",
};

export const EXPECTED_COUNTS: Record<Difficulty, number> = {
  easy: 20,
  medium: 25,
  hard: 30,
};

export const questionBank: QuestionSpec[] = [
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "Genesis 1:1",
    options: ["Genesis", "Exodus", "Job", "Psalms"],
    answer: "Genesis",
  },
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "John 1:1",
    options: ["Luke", "John", "Hebrews", "Revelation"],
    answer: "John",
  },
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "Philippians 4:13",
    options: ["Ephesians", "Galatians", "Philippians", "Colossians"],
    answer: "Philippians",
  },
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "Matthew 6:9",
    options: ["Mark", "Luke", "John", "Matthew"],
    answer: "Matthew",
  },
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "Revelation 21:4",
    options: ["Revelation", "Isaiah", "Daniel", "Ezekiel"],
    answer: "Revelation",
  },
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "Romans 8:28",
    options: ["Hebrews", "Romans", "James", "1 John"],
    answer: "Romans",
  },
  {
    type: "guess_the_book",
    difficulty: "easy",
    reference: "1 Corinthians 13:13",
    options: ["Romans", "Galatians", "1 Corinthians", "Ephesians"],
    answer: "1 Corinthians",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "Psalm 22 (23):1",
    strip: "A Psalm of David. ",
    blank: "lacking",
    options: ["wanting", "denied", "hidden", "lacking"],
    answer: "lacking",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "Psalm 118 (119):105",
    strip: "NUN. ",
    blank: "lamp",
    options: ["lamp", "torch", "guide", "shield"],
    answer: "lamp",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "John 14:6",
    blank: "Truth",
    options: ["Light", "Truth", "Word", "Door"],
    answer: "Truth",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "Proverbs 3:5",
    blank: "prudence",
    options: ["wisdom", "strength", "prudence", "counsel"],
    answer: "prudence",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "Matthew 5:9",
    blank: "peacemakers",
    options: ["meek", "merciful", "pure of heart", "peacemakers"],
    answer: "peacemakers",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "Genesis 1:3",
    blank: "became",
    options: ["became", "was", "appeared", "remained"],
    answer: "became",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "easy",
    reference: "Isaiah 40:31",
    blank: "eagles",
    options: ["doves", "eagles", "hawks", "angels"],
    answer: "eagles",
  },
  {
    type: "who_said_it",
    difficulty: "easy",
    reference: "John 15:13",
    options: ["Peter", "Paul", "Jesus", "John"],
    answer: "Jesus",
  },
  {
    type: "who_said_it",
    difficulty: "easy",
    reference: "Matthew 11:28",
    options: ["John the Baptist", "Isaiah", "Paul", "Jesus"],
    answer: "Jesus",
  },
  {
    type: "who_said_it",
    difficulty: "easy",
    reference: "Ruth 1:16",
    options: ["Ruth", "Naomi", "Esther", "Hannah"],
    answer: "Ruth",
  },
  {
    type: "who_said_it",
    difficulty: "easy",
    reference: "2 Timothy 4:7",
    options: ["Peter", "Paul", "James", "Timothy"],
    answer: "Paul",
  },
  {
    type: "who_said_it",
    difficulty: "easy",
    reference: "Job 19:25",
    options: ["David", "Isaiah", "Job", "Jeremiah"],
    answer: "Job",
  },
  {
    type: "who_said_it",
    difficulty: "easy",
    reference: "Exodus 20:3",
    options: ["Moses", "Aaron", "Joshua", "God"],
    answer: "God",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Ecclesiastes 3:1",
    options: ["Ecclesiastes", "Proverbs", "Job", "Song of Songs"],
    answer: "Ecclesiastes",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Jeremiah 29:11",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel"],
    answer: "Jeremiah",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Micah 6:8",
    options: ["Hosea", "Amos", "Micah", "Zechariah"],
    answer: "Micah",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Hebrews 11:1",
    options: ["Romans", "James", "1 Peter", "Hebrews"],
    answer: "Hebrews",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "James 2:17",
    options: ["James", "1 John", "Titus", "Jude"],
    answer: "James",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Ezekiel 36:26",
    options: ["Jeremiah", "Ezekiel", "Isaiah", "Joel"],
    answer: "Ezekiel",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Galatians 5:22",
    options: ["Ephesians", "Colossians", "Galatians", "Philippians"],
    answer: "Galatians",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "1 Peter 5:7",
    options: ["2 Peter", "1 John", "James", "1 Peter"],
    answer: "1 Peter",
  },
  {
    type: "guess_the_book",
    difficulty: "medium",
    reference: "Isaiah 9:6",
    options: ["Isaiah", "Micah", "Jeremiah", "Psalms"],
    answer: "Isaiah",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Romans 6:23",
    blank: "wages",
    options: ["price", "wages", "cost", "reward"],
    answer: "wages",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Matthew 22:21",
    blank: "render",
    options: ["give", "return", "render", "restore"],
    answer: "render",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Deuteronomy 6:5",
    blank: "strength",
    options: ["mind", "might", "being", "strength"],
    answer: "strength",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "1 Kings 19:12",
    blank: "gentle breeze",
    options: ["gentle breeze", "rushing wind", "quiet whisper", "distant thunder"],
    answer: "gentle breeze",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Psalm 50 (51):12",
    blank: "upright",
    options: ["steadfast", "upright", "humble", "willing"],
    answer: "upright",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Hosea 6:6",
    blank: "mercy",
    options: ["justice", "kindness", "mercy", "obedience"],
    answer: "mercy",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Zechariah 9:9",
    blank: "colt",
    options: ["foal", "lamb", "mule", "colt"],
    answer: "colt",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "medium",
    reference: "Habakkuk 3:19",
    blank: "stag",
    options: ["stag", "eagle", "lion", "ram"],
    answer: "stag",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Isaiah 6:8",
    options: ["Moses", "Isaiah", "Jeremiah", "Samuel"],
    answer: "Isaiah",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Colossians 3:23",
    options: ["Peter", "James", "Paul", "John"],
    answer: "Paul",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Matthew 4:4",
    options: ["Moses", "Paul", "John the Baptist", "Jesus"],
    answer: "Jesus",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Matthew 26:39",
    options: ["Jesus", "Peter", "Stephen", "Paul"],
    answer: "Jesus",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "1 Kings 3:9",
    options: ["David", "Solomon", "Samuel", "Nathan"],
    answer: "Solomon",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Job 1:21",
    options: ["David", "Jeremiah", "Job", "Tobit"],
    answer: "Job",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Deuteronomy 31:6",
    options: ["Joshua", "Caleb", "Aaron", "Moses"],
    answer: "Moses",
  },
  {
    type: "who_said_it",
    difficulty: "medium",
    reference: "Daniel 6:22",
    options: ["Daniel", "Shadrach", "Ezekiel", "Jeremiah"],
    answer: "Daniel",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Sirach 6:14",
    options: ["Sirach", "Proverbs", "Wisdom", "Ecclesiastes"],
    answer: "Sirach",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Wisdom 3:1",
    options: ["Sirach", "Wisdom", "Job", "Psalms"],
    answer: "Wisdom",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Tobit 13:2",
    options: ["Judith", "Daniel", "Tobit", "Baruch"],
    answer: "Tobit",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "2 Maccabees 12:46",
    options: ["1 Maccabees", "Sirach", "Wisdom", "2 Maccabees"],
    answer: "2 Maccabees",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Baruch 3:14",
    options: ["Baruch", "Jeremiah", "Lamentations", "Wisdom"],
    answer: "Baruch",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Judith 9:16",
    options: ["Esther", "Judith", "Ruth", "Tobit"],
    answer: "Judith",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "1 Maccabees 4:59",
    options: ["Nehemiah", "Ezra", "1 Maccabees", "2 Maccabees"],
    answer: "1 Maccabees",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Habakkuk 2:4",
    options: ["Nahum", "Zephaniah", "Haggai", "Habakkuk"],
    answer: "Habakkuk",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Nahum 1:7",
    options: ["Nahum", "Micah", "Joel", "Obadiah"],
    answer: "Nahum",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "Daniel 12:3",
    options: ["Ezekiel", "Daniel", "Isaiah", "Malachi"],
    answer: "Daniel",
  },
  {
    type: "guess_the_book",
    difficulty: "hard",
    reference: "1 Chronicles 16:34",
    options: ["1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles"],
    answer: "1 Chronicles",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Sirach 1:16",
    blank: "wisdom",
    options: ["knowledge", "justice", "life", "wisdom"],
    answer: "wisdom",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Wisdom 2:23",
    blank: "immortal",
    options: ["immortal", "upright", "holy", "free"],
    answer: "immortal",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Tobit 4:16",
    blank: "hate",
    options: ["fear", "hate", "refuse", "dread"],
    answer: "hate",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "1 Maccabees 3:19",
    blank: "multitude",
    options: ["courage", "discipline", "multitude", "number"],
    answer: "multitude",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Wisdom 7:26",
    blank: "mirror",
    options: ["image", "likeness", "seal", "mirror"],
    answer: "mirror",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Isaiah 53:5",
    blank: "wounds",
    options: ["wounds", "stripes", "sorrows", "chains"],
    answer: "wounds",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Jeremiah 1:5",
    blank: "prophet",
    options: ["light", "prophet", "sign", "witness"],
    answer: "prophet",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Joel 2:13",
    blank: "garments",
    options: ["robes", "tents", "garments", "veils"],
    answer: "garments",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Judith 16:16",
    blank: "splendor",
    options: ["glory", "majesty", "power", "splendor"],
    answer: "splendor",
  },
  {
    type: "fill_in_the_blank",
    difficulty: "hard",
    reference: "Wisdom 8:7",
    blank: "temperance",
    options: ["temperance", "patience", "humility", "mercy"],
    answer: "temperance",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "2 Maccabees 7:9",
    options: ["Eleazar", "One of the seven brothers", "Judas Maccabeus", "Mattathias"],
    answer: "One of the seven brothers",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "Nehemiah 8:10",
    options: ["Ezra", "Zerubbabel", "Nehemiah", "Cyrus"],
    answer: "Nehemiah",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "Acts 9:4",
    options: ["Stephen", "Ananias", "Gabriel", "Jesus"],
    answer: "Jesus",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "Tobit 12:7",
    options: ["The Angel Raphael", "Tobit", "Tobias", "Sarah"],
    answer: "The Angel Raphael",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "1 Maccabees 2:21",
    options: ["Judas Maccabeus", "Mattathias", "Simon", "Jonathan"],
    answer: "Mattathias",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "Mark 12:31",
    options: ["Moses", "Paul", "Jesus", "Peter"],
    answer: "Jesus",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "Exodus 14:14",
    options: ["Aaron", "Joshua", "Miriam", "Moses"],
    answer: "Moses",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "Joshua 1:9",
    options: ["The Lord", "Moses", "Caleb", "Eleazar"],
    answer: "The Lord",
  },
  {
    type: "who_said_it",
    difficulty: "hard",
    reference: "1 Corinthians 15:55",
    options: ["Peter", "Paul", "John", "James"],
    answer: "Paul",
  },
];
